Ceate secret store based on parameterstore
Clever/stealth pull request #41
Opened 2020-09-16 03:31 UTC by ulziibay

[SECNG-177](https://clever.atlassian.net/browse/SECNG-177)

Create a secret store that implements `SecretStore` interface.

```
type SecretStore interface {
	// Creates a Secret in the secret store. Version is guaranteed to be zero if no error is returned.
	Create(id SecretIdentifier, value string) error

	// Read a Secret from the store. Returns the lastest version of the secret.
	Read(id SecretIdentifier) (Secret, error)

	// ReadVersion reads a specific version of a secret from the store.
	// Version is 0-indexed
	ReadVersion(id SecretIdentifier, version int) (Secret, error)

	// Updates a Secret from the store and increments version number.
	Update(id SecretIdentifier, value string) (Secret, error)

	// List gets secrets within a namespace (env/service)>
	List(env Environment, service string) ([]SecretIdentifier, error)

	// ListAll gets all secrets within a environment (env)>
	ListAll(env Environment) ([]SecretIdentifier, error)

	// History gets history for a secret, returning all versions from the store.
	History(id SecretIdentifier) ([]SecretMeta, error)

	// Delete deletes all versions of a secret
	Delete(id SecretIdentifier) error
}
```

2020-09-16 04:04 UTC, nathanleiby commented on store/parameter_store.go
> +		Type:      aws.String("SecureString"),
Can use `ParameterTypeSecureString`
https://docs.aws.amazon.com/sdk-for-go/api/service/ssm/

2020-09-16 15:50 UTC, mcab commented
CI is currently saying this is failing due to user permissions, via Slack (https://clever.slack.com/archives/C9Z78L124/p1600228141155600) and CircleCI (https://app.circleci.com/pipelines/github/Clever/stealth/3/workflows/b49a2b5a-84b3-4a2b-af5b-a8f7b94f8f98/jobs/63).

I don't see a version to run this locally, but we could give this user permissions for e2e tests. (https://github.com/Clever/infra/blob/master/config/aws/iam/prod/application_users.tf#L103, AWS: https://console.aws.amazon.com/iam/home?region=us-west-1#/users/ci). Alternatively, you can mock out the service and just expect the calls to still run.

2020-09-16 17:02 UTC, ulziibay commented on store/parameter_store.go
> +		Type:      aws.String("SecureString"),
Will do!

2020-09-16 17:03 UTC, ulziibay commented
@mcab thanks for the pointers. I will make sure the CI user has permissions for e2e testing.

2020-09-16 18:22 UTC, ulziibay commented
@mcab added  https://github.com/Clever/infra/pull/1381 for the CI permissions

2020-09-17 01:21 UTC, mcab requested changes
Some things to consider with regards to reading secrets initially. It's tricky given the multiple regions in play here, but I'm not sure of the guarantees we want to provide for these functions.

---

Also, something to think about, we'll want to ask for service limit bumps for SSM. [In the docs](https://docs.aws.amazon.com/general/latest/gr/ssm.html#w430aab9d341b7b3) (search for "parameter store"), it's 40 actions / second for `GetParameter`, `GetParameters`, `GetParametersByPath`.

2020-09-17 01:21 UTC, mcab commented on store/parameter_store.go
> +	// The number of items returned, however, can be between zero and the value of MaxResults.
Do we need this?

If the response has `NextToken`, that means that there are more than 50 secrets for this namespace, and that we should ask Parameter store for the next one by requesting with `NextToken`. If we don't do that, we get a random assortment of secrets up to 50, and would ultimately return the first lookup.

---

If we're concerned about "best-effort basis" not returning all of the secrets, we could use a merge technique by:

1. Having `results` store a `map[<unique identifier for Secret>]SecretIdentifier{}`.
2. Iterating over the results from `DescribeParameters`.
3. If the translated Secret is not found in `results`, insert it into the map. If it is, skip it.
4. If we find a NextToken, request that, go back to 2.
5. Go back to 1, until three iterations are performed.

This will prevent us from reallocating every time we iterate over secrets, while trying its best to retain information about all of them.

2020-09-17 01:21 UTC, mcab commented on store/parameter_store.go
> +		}
This seems to return an error, rather than add to a list and return that.

2020-09-17 01:57 UTC, ulziibay commented on store/parameter_store.go
> +// Version is 0-indexed
Will address this!

2020-09-17 01:58 UTC, ulziibay commented on store/parameter_store.go
> +// Version is 0-indexed
Actually, this is addressed in `getParamNameFromNameAtVersion`

2020-09-17 01:59 UTC, ulziibay commented on store/store_test.go
> +			t.Log(fmt.Sprintf("write %d-th secret %s for service", i, newID.String()))
Addressed

2020-09-28 20:58 UTC, ulziibay commented on store/parameter_store.go
> +	}
Yeah i like that idea. I will either extend IdentifierNotFoundError with that info or create a new error!

2020-09-28 21:01 UTC, ulziibay commented on store/parameter_store.go
> +	exists := false
I like the idea. Good suggestion. I will adjust accordingly

2020-09-28 21:01 UTC, ulziibay commented on store/parameter_store.go
> +			}
Yeah.That refactoring will render this redundant!

2020-12-05 01:06 UTC, ulziibay commented on store/parameter_store.go
> +	exists := false
Addressed!

2020-12-05 01:06 UTC, ulziibay commented on store/parameter_store.go
> +		}
Yep. Addressed!

2020-12-05 01:06 UTC, ulziibay commented on store/parameter_store.go
> +	}
Extended `IdentifierNotFoundError`. Please take a look

2020-12-05 01:07 UTC, ulziibay commented on store/parameter_store.go
> +	// The number of items returned, however, can be between zero and the value of MaxResults.
Ended up modifying to use `DefaultRetryerMaxNumRetries` instead of hardcoded 3. 

The problem with the `NextToken` based implementation was that, I was not fully able to get `NextToken` to work reliably with the current version of the sdk.

2020-12-05 01:11 UTC, ulziibay commented on store/parameter_store.go
> +		}
Addressed!

2020-12-05 01:45 UTC, ulziibay commented
@mcab: I revised the approach based on your detailed feedback. Please review and let me know. Thanks!!

2020-12-08 00:12 UTC, ulziibay commented on store/test_utils.go
> +	return SecretIdentifier{Environment: CITestEnvironment, Service: "test" + randSeq(2), Key: randSeq(10)}
this is added to make sure when that when this unit test runs in parallel, the results are independent!

2020-12-08 01:16 UTC, mcab reviewed
It sucks we have to catching errors with Create/Update/Delete, but I'm really hoping we rarely run into those issues. If it ends up coming up, we'll just have to deal with them then.

`List()` has me particularly nervous because of `ListAll()` depending on it as well. If we pull all of the secrets for a particular environment, roughly, that's 2000 secrets / 50 secrets per request * number of retries = 120 requests.

That's going to take time, and we should look into self-throttling between NextToken checks.

There are some additional comments on version #s, and Read errors.

2020-12-08 01:28 UTC, ulziibay commented on store/parameter_store.go
> +		}
sure thing!

2020-12-08 01:30 UTC, ulziibay commented on store/parameter_store.go
> +	paramName := getParamNameFromNameAtVersion(id, version)
NO. i should make this as identical to `Read` implementation as possible!

2020-12-08 01:31 UTC, ulziibay commented on store/parameter_store.go
> +	return Secret{*resp.Parameter.Value, SecretMeta{Version: int(*resp.Parameter.Version)}}, nil
See getParamNameFromNameAtVersion at https://github.com/Clever/stealth/pull/41/files#diff-2bb38e9c60a5dc860569251984660086c499c5f8d573f3f8f0c1a88732006c16R67-R73. The version indexing is solved there!

2020-12-08 01:32 UTC, ulziibay commented on store/interface.go
>  }
Sure!

2020-12-08 01:32 UTC, ulziibay commented on store/memory_store.go
> +	return Secret{}, &IdentifierNotFoundError{Identifier: id, Region: Region}
Will do. but i am not really sure where in-memory store is used at the moment!

2020-12-08 01:33 UTC, ulziibay commented on store/parameter_store.go
> +func getOrderedRegions() []string {
Sure. I will add that comment

2020-12-08 01:51 UTC, ulziibay commented on store/parameter_store.go
> +// readForAllRegions reada given secret from all AWS regions and return status for the corresponding region.
good catch!

2020-12-08 02:33 UTC, ulziibay commented on store/parameter_store.go
> +	return Secret{*resp.Parameter.Value, SecretMeta{Version: int(*resp.Parameter.Version)}}, nil
See getParamNameFromNameAtVersion at https://github.com/Clever/stealth/pull/41/files#diff-2bb38e9c60a5dc860569251984660086c499c5f8d573f3f8f0c1a88732006c16R67-R73. The version indexing is solved there!

2020-12-08 03:59 UTC, ulziibay commented
@mcab : I think your concerns around performance of the operation is valid. My thoughts for the performance are as follow.

The SLA limit we have on the throughput forr SSM Parameter store is[ 40 / sec ](https://docs.aws.amazon.com/general/latest/gr/aws-general.pdf#aws-service-information). With that in mind, for the given call for `ListAll`, having `time.Sleep(1 * time.Second)` line on https://github.com/Clever/stealth/pull/41/files#diff-2bb38e9c60a5dc860569251984660086c499c5f8d573f3f8f0c1a88732006c16R298-R300 makes it such that we do not issue more than 40 request per second. Hence, we are barely under SLA for `ListAll`

As for the proper usage of the API, the documentation for `DecribeParameters` API call, says that
> Multiple API calls may be issued in order to retrieve the entire data set of results.

Since we do want the entire data set, issueing multiple calls is not breaking the recommended usage.

Lastly, I agree with you that the operation will be slow. To that end, I propose that I can reduce the number of retries to be `2` instead of `3`. What do you think?

2020-12-08 20:14 UTC, mcab commented on store/parameter_store.go
> +	return Secret{*resp.Parameter.Value, SecretMeta{Version: int(*resp.Parameter.Version)}}, nil
That's right to translate the user's request to the service's input, but what if we wanted to use the information from the service?

For example, SSM has two versions of the secret stored at `/mark/app1/password`.
```
SSM
-----
name                    value       version
/mark/app1/password     p@ss        2
```

A hypothetical ark implementation:
```
# I want to get the second version from my perspective
ark secrets history mark.app1 password --version 1
```

This function would return the value as:
```
return Secret{"p@ss", SecretMeta{Version: 2}}, nil
```

We then end up not standardizing AWS's response of `Version` to our internal indexing of `Version`. If we were to use the secret's `Version` during implementation, we would report on AWS's version instead of what we consider as the `Version`. Standardizing the service's response in the library keeps a consistent definition for this field, and allows us to use it for future uses.

2020-12-08 20:15 UTC, mcab commented on store/test_utils.go
> +	// stores["Unicreds"] = NewUnicredsStore()
Intended?

2020-12-08 20:23 UTC, ulziibay commented on store/test_utils.go
> +	// stores["Unicreds"] = NewUnicredsStore()
No. Will undo

2020-12-08 20:30 UTC, mcab commented
> The SLA limit we have on the throughput forr SSM Parameter store is[ 40 / sec ](https://docs.aws.amazon.com/general/latest/gr/aws-general.pdf#aws-service-information). With that in mind, for the given call for `ListAll`, having `time.Sleep(1 * time.Second)` line on https://github.com/Clever/stealth/pull/41/files#diff-2bb38e9c60a5dc860569251984660086c499c5f8d573f3f8f0c1a88732006c16R298-R300 makes it such that we do not issue more than 40 request per second. Hence, we are barely under SLA for `ListAll`

I'm more concerned with us as an org into those limits. From https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-throughput.html:

> The Parameter Store throughput setting applies to all transactions created by all AWS Identity and Access Management (IAM) users in the current AWS account and Region. The throughput setting applies to standard and advanced parameters.

This means we share this rate with every user, as well as mechanical users too (catapult might fall under this path). Deploys might need to read from Parameter Store, which would hit on our limit.

If there are multiple pages, I think that we should slow it slightly down, like how we do the same for dupe checking (https://github.com/Clever/stealth/blob/46e747545dc990a12454771469e77351fdf90021/store/util/dupes.go#L22-L23).

> Lastly, I agree with you that the operation will be slow. To that end, I propose that I can reduce the number of retries to be `2` instead of `3`. What do you think?

This is probably the best ideal here. If there is some drift between the first read and the second read, ideally, the second one wins out with as much up-to-date information as possible.

2020-12-08 20:32 UTC, ulziibay commented on store/parameter_store.go
> +	return Secret{*resp.Parameter.Value, SecretMeta{Version: int(*resp.Parameter.Version)}}, nil
Yeah good call. I think in this case it would return 
```
return Secret{"p@ss", SecretMeta{Version: 2}}, p@ss
```
because we will get the SSM param at version 2 correctly.
I will adjust the version to be reported correctly

2020-12-08 21:03 UTC, mcab approved these changes
![it's time](https://media1.giphy.com/media/CjmvTCZf2U3p09Cn0h/giphy.gif)

to a parameter store-powered future! 😀

2020-12-08 21:45 UTC, ulziibay commented
Thank you so much for the thorough reviews! @mcab. Really appreciate it 🙏 

![Alt Text](https://media.giphy.com/media/0DYipdNqJ5n4GYATKL/giphy.gif)

2020-12-08 21:46 UTC, merged